# Generated by Django 5.2.7 on 2026-06-24 07:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationModel',
            fields=[
                ('conversations_id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('conversations_name', models.CharField(db_column='conversations_name', db_index=True, default='', max_length=255)),
                ('conversations_title', models.CharField(db_column='conversations_title', default='', max_length=255)),
                ('conversations_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversations',
            },
        ),
        migrations.CreateModel(
            name='ConversationCacheModel',
            fields=[
                ('conversation_cache_id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('conversation_cache_is_active', models.BooleanField(default=True)),
                ('conversation_cache_file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('conversation_cache_created_at', models.DateTimeField(auto_now=True)),
                ('conversation_cache_status', models.UUIDField(blank=True, null=True)),
                ('conversation_cache_conversation', models.OneToOneField(db_column='conversation_cache_conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_cache', to='chat.conversationmodel')),
            ],
            options={
                'db_table': 'conversation_cache',
            },
        ),
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('documents_is_active', models.BooleanField(default=True)),
                ('documents_created_at', models.DateTimeField(auto_now_add=True)),
                ('documents_file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('documents_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], db_column='documents_status', default='uploaded', max_length=32)),
                ('documents_content', models.TextField(blank=True, null=True)),
                ('documents_conversation', models.OneToOneField(db_column='documents_conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='document', to='chat.conversationmodel')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='ConversationFilesModel',
            fields=[
                ('conversation_files_id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('conversation_files_cloud_id', models.CharField(db_column='conversation_files_cloud_id', db_index=True, max_length=255)),
                ('conversation_files_uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('conversation_files_document', models.ForeignKey(db_column='conversation_files_document_id', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_files', to='chat.documentmodel')),
            ],
            options={
                'db_table': 'conversation_files',
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('messages_id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('messages_is_user_send', models.BooleanField()),
                ('messages_content', models.TextField()),
                ('messages_created_at', models.DateTimeField(auto_now_add=True)),
                ('messages_conversation', models.ForeignKey(db_column='message_conversation_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversationmodel')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
