# Generated by Django 5.2.7 on 2026-06-03 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationModel',
            fields=[
                ('conversation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_title', models.CharField(max_length=255)),
                ('conversation_created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversation',
            },
        ),
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('faiss_index_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('faiss_index_file_name', models.CharField(max_length=255)),
                ('faiss_index_is_active', models.BooleanField(default=True)),
                ('faiss_index_created_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(default='uploaded', max_length=32)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faiss_index',
            },
        ),
        migrations.CreateModel(
            name='ConversationFilesModel',
            fields=[
                ('conversation_files_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation', models.ForeignKey(db_column='conversation_files_conversation_id', on_delete=django.db.models.deletion.CASCADE, to='chat.conversationmodel')),
                ('faiss_index', models.ForeignKey(db_column='faiss_index_id', on_delete=django.db.models.deletion.CASCADE, to='chat.documentmodel')),
            ],
            options={
                'db_table': 'conversation_files',
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_is_user_send', models.BooleanField()),
                ('message_content', models.TextField()),
                ('message_created_at', models.DateTimeField(auto_now_add=True)),
                ('message_conversation', models.ForeignKey(db_column='message_conversation_id', on_delete=django.db.models.deletion.CASCADE, to='chat.conversationmodel')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
