# Generated by Django 5.2.7 on 2026-06-21 19:47

import app
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentmodel',
            old_name='faiss_index_created_at',
            new_name='documents_created_at',
        ),
        migrations.RenameField(
            model_name='documentmodel',
            old_name='file_path',
            new_name='documents_file_path',
        ),
        migrations.RenameField(
            model_name='documentmodel',
            old_name='faiss_index_is_active',
            new_name='documents_is_active',
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='message_created_at',
            new_name='messages_created_at',
        ),
        migrations.RemoveField(
            model_name='conversationfilesmodel',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversationfilesmodel',
            name='faiss_index',
        ),
        migrations.RemoveField(
            model_name='conversationmodel',
            name='conversation_created_at',
        ),
        migrations.RemoveField(
            model_name='conversationmodel',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='conversationmodel',
            name='conversation_name',
        ),
        migrations.RemoveField(
            model_name='conversationmodel',
            name='conversation_title',
        ),
        migrations.RemoveField(
            model_name='documentmodel',
            name='content',
        ),
        migrations.RemoveField(
            model_name='documentmodel',
            name='faiss_index_file_name',
        ),
        migrations.RemoveField(
            model_name='documentmodel',
            name='faiss_index_id',
        ),
        migrations.RemoveField(
            model_name='documentmodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='message_content',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='message_conversation',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='message_id',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='message_is_user_send',
        ),
        migrations.AddField(
            model_name='conversationfilesmodel',
            name='conversation_files_cloud_id',
            field=models.CharField(blank=True, db_column='conversation_files_cloud_id', db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversationfilesmodel',
            name='conversation_files_conversation',
            field=models.ForeignKey(blank=True, db_column='conversation_files_conversation_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.conversationmodel'),
        ),
        migrations.AddField(
            model_name='conversationfilesmodel',
            name='conversation_files_uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationmodel',
            name='conversations_created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationmodel',
            name='conversations_id',
            field=models.UUIDField(default=app._uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='conversationmodel',
            name='conversations_name',
            field=models.CharField(blank=True, db_column='conversations_name', db_index=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conversationmodel',
            name='conversations_title',
            field=models.CharField(blank=True, db_column='conversations_title', default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='document_id',
            field=models.UUIDField(default=app._uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='documents_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='documents_conversation',
            field=models.ForeignKey(blank=True, db_column='documents_conversation_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.conversationmodel'),
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='documents_status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], db_column='documents_status', default='uploaded', max_length=32),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='messages_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='messages_conversation',
            field=models.ForeignKey(blank=True, db_column='message_conversation_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.conversationmodel'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='messages_id',
            field=models.UUIDField(default=app._uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='messages_is_user_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conversationfilesmodel',
            name='conversation_files_id',
            field=models.UUIDField(default=app._uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='conversationmodel',
            table='conversations',
        ),
        migrations.AlterModelTable(
            name='documentmodel',
            table='documents',
        ),
    ]
