# Generated by Django 5.2.7 on 2026-06-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationcachemodel',
            name='conversation_cache_status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], db_column='conversation_status', default='uploaded', max_length=32),
        ),
    ]
