# Generated by Django 5.2.7 on 2026-06-22 02:30

import app
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_faiss_index_created_at_documentmodel_documents_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmodel',
            name='conversations_created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='conversations_created_at'),
        ),
        migrations.RenameField(
            model_name='conversationmodel',
            old_name='conversations_created_at',
            new_name='conversation_created_at',
        ),
        migrations.AlterField(
            model_name='conversationmodel',
            name='conversations_id',
            field=models.UUIDField(db_column='conversations_id', default=app._uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='conversationmodel',
            old_name='conversations_id',
            new_name='conversation_id',
        ),
        migrations.RenameField(
            model_name='conversationmodel',
            old_name='conversations_name',
            new_name='conversation_name',
        ),
        migrations.RenameField(
            model_name='conversationmodel',
            old_name='conversations_title',
            new_name='conversation_title',
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='documents_content',
            field=models.TextField(blank=True, db_column='documents_content', null=True),
        ),
        migrations.RenameField(
            model_name='documentmodel',
            old_name='documents_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='documentmodel',
            old_name='documents_conversation',
            new_name='conversation',
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='documents_created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='documents_created_at'),
        ),
        migrations.RenameField(
            model_name='documentmodel',
            old_name='documents_created_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='documents_file_path',
            field=models.CharField(blank=True, db_column='documents_file_path', max_length=512, null=True),
        ),
        migrations.RenameField(
            model_name='documentmodel',
            old_name='documents_file_path',
            new_name='file_path',
        ),
        migrations.AlterField(
            model_name='documentmodel',
            name='documents_is_active',
            field=models.BooleanField(db_column='documents_is_active', default=True),
        ),
        migrations.RenameField(
            model_name='documentmodel',
            old_name='documents_is_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='documentmodel',
            old_name='documents_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='messages_content',
            field=models.TextField(blank=True, db_column='messages_content', null=True),
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='messages_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='messages_conversation',
            new_name='conversation',
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='messages_created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='messages_created_at'),
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='messages_created_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='messages_is_user_send',
            field=models.BooleanField(db_column='messages_is_user_send', default=False),
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='messages_is_user_send',
            new_name='is_user_send',
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='messages_id',
            field=models.UUIDField(db_column='messages_id', default=app._uuid7, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='messages_id',
            new_name='message_id',
        ),
        migrations.RemoveField(
            model_name='conversationfilesmodel',
            name='conversation_files_cloud_id',
        ),
        migrations.RemoveField(
            model_name='conversationfilesmodel',
            name='conversation_files_conversation',
        ),
        migrations.AddField(
            model_name='conversationfilesmodel',
            name='conversation',
            field=models.ForeignKey(blank=True, db_column='conversation_files_conversation_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.conversationmodel'),
        ),
        migrations.AddField(
            model_name='conversationfilesmodel',
            name='faiss_index',
            field=models.ForeignKey(blank=True, db_column='conversation_files_cloud_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.documentmodel'),
        ),
    ]
